### PR TITLE
fix default region

### PR DESCRIPTION
**Pull request by undying**
there is a problem, when region is set through config file, it was ignored in the code.
this pull request is designed to fix that problem

### CODE REVIEW

**Comment by dmveygo** [comment]
Hello,

I don't see how this could fix a problem, isn't it just a cosmetic change ? Could you explain what is your problem exactly and how this would fix it ?

Thank you!

**Comment by undying** [comment]
Hello.
You may try to set region in configuration file that differs from default region and see that it won't be applied.

**Comment by dmveygo** [comment]
I'm not using the default region:

production:
  access_key_id: <%= ENV['ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['SECRET_ACCESS_KEY'] %>
  bucket: <%= ENV['BUCKET'] %> 
  region: eu-west-1

And it's working for me. Besides, you did not explain what your fix is supposed to do. To me, it looks like your fix does not change anything to the way the code is working, but maybe I'm missing something.

**Comment by undying** [comment]
you set `options[:region]` only `if self.region.nil?` but if it's not nil (region is passed in configuration yaml file), `options[:region]` is not being set, so method `Aws::S3::Client.new()` falls with empty region.

**Comment by dmveygo** [comment]
I see now, thanks for enlightening me :)

**Comment by canatella** [comment]
Thank you!

**Comment by undying** [comment]
you are welcome =]

**Pull request merged**
